import { ElementData } from '../types/element';

export const elements: ElementData[] = [
  {
    atomicNumber: 1,
    symbol: 'H',
    name: 'Hydrogen',
    atomicMass: 1.008,
    density: 0.08988,
    phase: 'Gas',
    meltingPoint: 13.99,
    boilingPoint: 20.271,
    discoveryYear: 1766,
    discoverer: 'Henry Cavendish',
    summary: 'Hydrogen is the chemical element with the symbol H and atomic number 1. It is the lightest element and, at standard conditions, is a gas of diatomic molecules with the formula H2. It is the most abundant chemical substance in the universe, constituting roughly 75% of all baryonic mass.',
    externalLink: 'https://en.wikipedia.org/wiki/Hydrogen',
    category: 'Nonmetal',
    electronConfiguration: [1],
    xpos: 1,
    ypos: 1,
  },
  {
    atomicNumber: 2,
    symbol: 'He',
    name: 'Helium',
    atomicMass: 4.002602,
    density: 0.1786,
    phase: 'Gas',
    meltingPoint: 0.95,
    boilingPoint: 4.222,
    discoveryYear: 1868,
    discoverer: 'Pierre Janssen, Norman Lockyer',
    summary: 'Helium is a chemical element with the symbol He and atomic number 2. It is a colorless, odorless, tasteless, non-toxic, inert, monatomic gas, the first in the noble gas group in the periodic table. Its boiling point is the lowest among all the elements.',
    externalLink: 'https://en.wikipedia.org/wiki/Helium',
    category: 'Noble Gas',
    electronConfiguration: [2],
    xpos: 18,
    ypos: 1,
  },
  {
    atomicNumber: 3,
    symbol: 'Li',
    name: 'Lithium',
    atomicMass: 6.94,
    density: 0.534,
    phase: 'Solid',
    meltingPoint: 453.65,
    boilingPoint: 1615,
    discoveryYear: 1817,
    discoverer: 'Johan August Arfwedson',
    summary: 'Lithium is a chemical element with the symbol Li and atomic number 3. It is a soft, silvery-white alkali metal. Under standard conditions, it is the lightest metal and the lightest solid element.',
    externalLink: 'https://en.wikipedia.org/wiki/Lithium',
    category: 'Alkali Metal',
    electronConfiguration: [2, 1],
    xpos: 1,
    ypos: 2,
  },
  {
    atomicNumber: 4,
    symbol: 'Be',
    name: 'Beryllium',
    atomicMass: 9.0121831,
    density: 1.85,
    phase: 'Solid',
    meltingPoint: 1560,
    boilingPoint: 2742,
    discoveryYear: 1798,
    discoverer: 'Louis-Nicolas Vauquelin',
    summary: 'Beryllium is a chemical element with the symbol Be and atomic number 4. It is a relatively rare element in the universe, usually occurring as a product of the spallation of larger atomic nuclei that have collided with cosmic rays.',
    externalLink: 'https://en.wikipedia.org/wiki/Beryllium',
    category: 'Alkaline Earth Metal',
    electronConfiguration: [2, 2],
    xpos: 2,
    ypos: 2,
  },
  {
    atomicNumber: 5,
    symbol: 'B',
    name: 'Boron',
    atomicMass: 10.81,
    density: 2.08,
    phase: 'Solid',
    meltingPoint: 2348,
    boilingPoint: 4200,
    discoveryYear: 1808,
    discoverer: 'Humphry Davy, Joseph Louis Gay-Lussac, Louis Jacques Thénard',
    summary: 'Boron is a chemical element with the symbol B and atomic number 5. Produced entirely by cosmic ray spallation and supernovae rather than by stellar nucleosynthesis, it is a low-abundance element in the Solar System and in the Earth\'s crust.',
    externalLink: 'https://en.wikipedia.org/wiki/Boron',
    category: 'Metalloid',
    electronConfiguration: [2, 3],
    xpos: 13,
    ypos: 2,
  },
  {
    atomicNumber: 6,
    symbol: 'C',
    name: 'Carbon',
    atomicMass: 12.011,
    density: 2.267,
    phase: 'Solid',
    meltingPoint: 3823,
    boilingPoint: 4300,
    discoveryYear: 'Ancient',
    discoverer: 'Unknown',
    summary: 'Carbon is a chemical element with the symbol C and atomic number 6. It is nonmetallic and tetravalent—making four electrons available to form covalent chemical bonds. It belongs to group 14 of the periodic table.',
    externalLink: 'https://en.wikipedia.org/wiki/Carbon',
    category: 'Nonmetal',
    electronConfiguration: [2, 4],
    xpos: 14,
    ypos: 2,
  },
  {
    atomicNumber: 7,
    symbol: 'N',
    name: 'Nitrogen',
    atomicMass: 14.007,
    density: 1.251,
    phase: 'Gas',
    meltingPoint: 63.15,
    boilingPoint: 77.35,
    discoveryYear: 1772,
    discoverer: 'Daniel Rutherford',
    summary: 'Nitrogen is a chemical element with the symbol N and atomic number 7. It is the lightest member of Group 15 of the periodic table, often called the pnictogens. It is a common element in the universe, estimated to be about seventh in total abundance in the Milky Way and the Solar System.',
    externalLink: 'https://en.wikipedia.org/wiki/Nitrogen',
    category: 'Nonmetal',
    electronConfiguration: [2, 5],
    xpos: 15,
    ypos: 2,
  },
  {
    atomicNumber: 8,
    symbol: 'O',
    name: 'Oxygen',
    atomicMass: 15.999,
    density: 1.429,
    phase: 'Gas',
    meltingPoint: 54.36,
    boilingPoint: 90.188,
    discoveryYear: 1774,
    discoverer: 'Joseph Priestley, Carl Wilhelm Scheele',
    summary: 'Oxygen is a chemical element with the symbol O and atomic number 8. It is a member of the chalcogen group in the periodic table, a highly reactive nonmetal, and an oxidizing agent that readily forms oxides with most elements as well as with other compounds.',
    externalLink: 'https://en.wikipedia.org/wiki/Oxygen',
    category: 'Nonmetal',
    electronConfiguration: [2, 6],
    xpos: 16,
    ypos: 2,
  },
  {
    atomicNumber: 9,
    symbol: 'F',
    name: 'Fluorine',
    atomicMass: 18.998403163,
    density: 1.696,
    phase: 'Gas',
    meltingPoint: 53.53,
    boilingPoint: 85.03,
    discoveryYear: 1886,
    discoverer: 'Henri Moissan',
    summary: 'Fluorine is a chemical element with the symbol F and atomic number 9. It is the lightest halogen and exists as a highly toxic pale yellow diatomic gas at standard conditions. As the most electronegative element, it is extremely reactive, as it reacts with all other elements, except for light inert gases.',
    externalLink: 'https://en.wikipedia.org/wiki/Fluorine',
    category: 'Nonmetal',
    electronConfiguration: [2, 7],
    xpos: 17,
    ypos: 2,
  },
  {
    atomicNumber: 10,
    symbol: 'Ne',
    name: 'Neon',
    atomicMass: 20.1797,
    density: 0.9,
    phase: 'Gas',
    meltingPoint: 24.56,
    boilingPoint: 27.07,
    discoveryYear: 1898,
    discoverer: 'William Ramsay, Morris Travers',
    summary: 'Neon is a chemical element with the symbol Ne and atomic number 10. It is a noble gas. Neon is a colorless, odorless, inert monatomic gas under standard conditions, with about two-thirds the density of air.',
    externalLink: 'https://en.wikipedia.org/wiki/Neon',
    category: 'Noble Gas',
    electronConfiguration: [2, 8],
    xpos: 18,
    ypos: 2,
  },
  {
    atomicNumber: 11,
    symbol: 'Na',
    name: 'Sodium',
    atomicMass: 22.98976928,
    density: 0.968,
    phase: 'Solid',
    meltingPoint: 370.944,
    boilingPoint: 1156.09,
    discoveryYear: 1807,
    discoverer: 'Humphry Davy',
    summary: 'Sodium is a chemical element with the symbol Na and atomic number 11. It is a soft, silvery-white, highly reactive metal. Sodium is an alkali metal, being in group 1 of the periodic table.',
    externalLink: 'https://en.wikipedia.org/wiki/Sodium',
    category: 'Alkali Metal',
    electronConfiguration: [2, 8, 1],
    xpos: 1,
    ypos: 3,
  },
  {
    atomicNumber: 12,
    symbol: 'Mg',
    name: 'Magnesium',
    atomicMass: 24.305,
    density: 1.738,
    phase: 'Solid',
    meltingPoint: 923,
    boilingPoint: 1363,
    discoveryYear: 1755,
    discoverer: 'Joseph Black',
    summary: 'Magnesium is a chemical element with the symbol Mg and atomic number 12. It is a shiny gray solid which bears a close physical resemblance to the other five elements in the second column (group 2, or alkaline earth metals) of the periodic table.',
    externalLink: 'https://en.wikipedia.org/wiki/Magnesium',
    category: 'Alkaline Earth Metal',
    electronConfiguration: [2, 8, 2],
    xpos: 2,
    ypos: 3,
  },
  {
    atomicNumber: 13,
    symbol: 'Al',
    name: 'Aluminum',
    atomicMass: 26.9815385,
    density: 2.7,
    phase: 'Solid',
    meltingPoint: 933.47,
    boilingPoint: 2792,
    discoveryYear: 1825,
    discoverer: 'Hans Christian Ørsted',
    summary: 'Aluminium is a chemical element with the symbol Al and atomic number 13. It is a silvery-white, soft, non-magnetic, ductile metal in the boron group. By mass, aluminium makes up about 8% of the Earth\'s crust; it is the third most abundant element after oxygen and silicon.',
    externalLink: 'https://en.wikipedia.org/wiki/Aluminium',
    category: 'Post-Transition Metal',
    electronConfiguration: [2, 8, 3],
    xpos: 13,
    ypos: 3,
  },
  {
    atomicNumber: 14,
    symbol: 'Si',
    name: 'Silicon',
    atomicMass: 28.085,
    density: 2.329,
    phase: 'Solid',
    meltingPoint: 1687,
    boilingPoint: 3538,
    discoveryYear: 1823,
    discoverer: 'Jöns Jacob Berzelius',
    summary: 'Silicon is a chemical element with the symbol Si and atomic number 14. It is a tetravalent metalloid, making it less reactive than its chemical analog carbon. It is the eighth most common element in the universe by mass, but very rarely occurs as the pure free element in nature.',
    externalLink: 'https://en.wikipedia.org/wiki/Silicon',
    category: 'Metalloid',
    electronConfiguration: [2, 8, 4],
    xpos: 14,
    ypos: 3,
  },
  {
    atomicNumber: 15,
    symbol: 'P',
    name: 'Phosphorus',
    atomicMass: 30.973761998,
    density: 1.823,
    phase: 'Solid',
    meltingPoint: 317.3,
    boilingPoint: 553.6,
    discoveryYear: 1669,
    discoverer: 'Hennig Brand',
    summary: 'Phosphorus is a chemical element with the symbol P and atomic number 15. Elemental phosphorus exists in two major forms: white phosphorus and red phosphorus. It is a highly reactive nonmetal.',
    externalLink: 'https://en.wikipedia.org/wiki/Phosphorus',
    category: 'Nonmetal',
    electronConfiguration: [2, 8, 5],
    xpos: 15,
    ypos: 3,
  },
  {
    atomicNumber: 16,
    symbol: 'S',
    name: 'Sulfur',
    atomicMass: 32.06,
    density: 2.07,
    phase: 'Solid',
    meltingPoint: 388.36,
    boilingPoint: 717.8,
    discoveryYear: 'Ancient',
    discoverer: 'Unknown',
    summary: 'Sulfur is a chemical element with the symbol S and atomic number 16. It is abundant, multivalent, and nonmetallic. Under normal conditions, sulfur atoms form cyclic octatomic molecules with a chemical formula S8.',
    externalLink: 'https://en.wikipedia.org/wiki/Sulfur',
    category: 'Nonmetal',
    electronConfiguration: [2, 8, 6],
    xpos: 16,
    ypos: 3,
  },
  {
    atomicNumber: 17,
    symbol: 'Cl',
    name: 'Chlorine',
    atomicMass: 35.45,
    density: 3.2,
    phase: 'Gas',
    meltingPoint: 171.6,
    boilingPoint: 239.11,
    discoveryYear: 1774,
    discoverer: 'Carl Wilhelm Scheele',
    summary: 'Chlorine is a chemical element with the symbol Cl and atomic number 17. The second lightest of the halogens, it is a yellow-green gas at room temperature. It is an extremely reactive element and a strong oxidizing agent.',
    externalLink: 'https://en.wikipedia.org/wiki/Chlorine',
    category: 'Nonmetal',
    electronConfiguration: [2, 8, 7],
    xpos: 17,
    ypos: 3,
  },
  {
    atomicNumber: 18,
    symbol: 'Ar',
    name: 'Argon',
    atomicMass: 39.948,
    density: 1.784,
    phase: 'Gas',
    meltingPoint: 83.8,
    boilingPoint: 87.302,
    discoveryYear: 1894,
    discoverer: 'Lord Rayleigh, William Ramsay',
    summary: 'Argon is a chemical element with the symbol Ar and atomic number 18. It is in group 18 of the periodic table and is a noble gas. Argon is the third most abundant gas in the Earth\'s atmosphere, at 0.934% (9,340 ppm).',
    externalLink: 'https://en.wikipedia.org/wiki/Argon',
    category: 'Noble Gas',
    electronConfiguration: [2, 8, 8],
    xpos: 18,
    ypos: 3,
  },
  {
    atomicNumber: 19,
    symbol: 'K',
    name: 'Potassium',
    atomicMass: 39.0983,
    density: 0.862,
    phase: 'Solid',
    meltingPoint: 336.53,
    boilingPoint: 1032,
    discoveryYear: 1807,
    discoverer: 'Humphry Davy',
    summary: 'Potassium is a chemical element with the symbol K and atomic number 19. Potassium is a silvery-white metal that is soft enough to be cut with a knife with little force. Potassium metal reacts rapidly with atmospheric oxygen to form flaky white potassium peroxide in air, and with water to produce hydrogen.',
    externalLink: 'https://en.wikipedia.org/wiki/Potassium',
    category: 'Alkali Metal',
    electronConfiguration: [2, 8, 8, 1],
    xpos: 1,
    ypos: 4,
  },
  {
    atomicNumber: 20,
    symbol: 'Ca',
    name: 'Calcium',
    atomicMass: 40.078,
    density: 1.55,
    phase: 'Solid',
    meltingPoint: 1115,
    boilingPoint: 1757,
    discoveryYear: 1808,
    discoverer: 'Humphry Davy',
    summary: 'Calcium is a chemical element with the symbol Ca and atomic number 20. As an alkaline earth metal, it is a reactive metal that forms a dark oxide-nitride layer when exposed to air. Its physical and chemical properties are most similar to its heavier homologs strontium and barium.',
    externalLink: 'https://en.wikipedia.org/wiki/Calcium',
    category: 'Alkaline Earth Metal',
    electronConfiguration: [2, 8, 8, 2],
    xpos: 2,
    ypos: 4,
  },
  {
    atomicNumber: 21,
    symbol: 'Sc',
    name: 'Scandium',
    atomicMass: 44.955908,
    density: 2.989,
    phase: 'Solid',
    meltingPoint: 1814,
    boilingPoint: 3109,
    discoveryYear: 1879,
    discoverer: 'Lars Fredrik Nilson',
    summary: 'Scandium is a chemical element with the symbol Sc and atomic number 21. A silvery-white metallic d-block element, it has historically been classified as a rare earth element, together with yttrium and the lanthanides.',
    externalLink: 'https://en.wikipedia.org/wiki/Scandium',
    category: 'Transition Metal',
    electronConfiguration: [2, 8, 9, 2],
    xpos: 3,
    ypos: 4,
  },
  {
    atomicNumber: 22,
    symbol: 'Ti',
    name: 'Titanium',
    atomicMass: 47.867,
    density: 4.506,
    phase: 'Solid',
    meltingPoint: 1941,
    boilingPoint: 3560,
    discoveryYear: 1791,
    discoverer: 'William Gregor',
    summary: 'Titanium is a chemical element with the symbol Ti and atomic number 22. It is a lustrous transition metal with a silver color, low density, and high strength. Titanium is resistant to corrosion in sea water, aqua regia, and chlorine.',
    externalLink: 'https://en.wikipedia.org/wiki/Titanium',
    category: 'Transition Metal',
    electronConfiguration: [2, 8, 10, 2],
    xpos: 4,
    ypos: 4,
  },
  {
    atomicNumber: 23,
    symbol: 'V',
    name: 'Vanadium',
    atomicMass: 50.9415,
    density: 6.11,
    phase: 'Solid',
    meltingPoint: 2183,
    boilingPoint: 3680,
    discoveryYear: 1801,
    discoverer: 'Andrés Manuel del Río',
    summary: 'Vanadium is a chemical element with the symbol V and atomic number 23. It is a hard, silvery-grey, ductile transition metal. The elemental metal is rarely found in nature, but once isolated artificially, the formation of an oxide layer (passivation) somewhat stabilizes the free metal against oxidation.',
    externalLink: 'https://en.wikipedia.org/wiki/Vanadium',
    category: 'Transition Metal',
    electronConfiguration: [2, 8, 11, 2],
    xpos: 5,
    ypos: 4,
  },
  {
    atomicNumber: 24,
    symbol: 'Cr',
    name: 'Chromium',
    atomicMass: 51.9961,
    density: 7.19,
    phase: 'Solid',
    meltingPoint: 2180,
    boilingPoint: 2944,
    discoveryYear: 1797,
    discoverer: 'Louis Nicolas Vauquelin',
    summary: 'Chromium is a chemical element with the symbol Cr and atomic number 24. It is the first element in Group 6. It is a steely-grey, lustrous, hard, and brittle transition metal.',
    externalLink: 'https://en.wikipedia.org/wiki/Chromium',
    category: 'Transition Metal',
    electronConfiguration: [2, 8, 13, 1],
    xpos: 6,
    ypos: 4,
  },
  {
    atomicNumber: 25,
    symbol: 'Mn',
    name: 'Manganese',
    atomicMass: 54.938044,
    density: 7.47,
    phase: 'Solid',
    meltingPoint: 1519,
    boilingPoint: 2334,
    discoveryYear: 1774,
    discoverer: 'Johan Gottlieb Gahn',
    summary: 'Manganese is a chemical element with the symbol Mn and atomic number 25. It is a hard, brittle, silvery-grey metal, often found in minerals in combination with iron. Manganese is a transition metal with a diverse range of industrial uses.',
    externalLink: 'https://en.wikipedia.org/wiki/Manganese',
    category: 'Transition Metal',
    electronConfiguration: [2, 8, 13, 2],
    xpos: 7,
    ypos: 4,
  },
  {
    atomicNumber: 26,
    symbol: 'Fe',
    name: 'Iron',
    atomicMass: 55.845,
    density: 7.874,
    phase: 'Solid',
    meltingPoint: 1811,
    boilingPoint: 3134,
    discoveryYear: 'Ancient',
    discoverer: 'Unknown',
    summary: 'Iron is a chemical element with the symbol Fe and atomic number 26. It is a metal in the first transition series. It is the most common element on Earth by mass, forming much of Earth\'s outer and inner core.',
    externalLink: 'https://en.wikipedia.org/wiki/Iron',
    category: 'Transition Metal',
    electronConfiguration: [2, 8, 14, 2],
    xpos: 8,
    ypos: 4,
  },
  {
    atomicNumber: 27,
    symbol: 'Co',
    name: 'Cobalt',
    atomicMass: 58.933194,
    density: 8.9,
    phase: 'Solid',
    meltingPoint: 1768,
    boilingPoint: 3200,
    discoveryYear: 1735,
    discoverer: 'Georg Brandt',
    summary: 'Cobalt is a chemical element with the symbol Co and atomic number 27. It is a hard, ferromagnetic, silver-white, lustrous metal. Cobalt is found in the Earth\'s crust only in chemically combined form, save for small deposits found in alloys of natural meteoric iron.',
    externalLink: 'https://en.wikipedia.org/wiki/Cobalt',
    category: 'Transition Metal',
    electronConfiguration: [2, 8, 15, 2],
    xpos: 9,
    ypos: 4,
  },
  {
    atomicNumber: 28,
    symbol: 'Ni',
    name: 'Nickel',
    atomicMass: 58.6934,
    density: 8.908,
    phase: 'Solid',
    meltingPoint: 1728,
    boilingPoint: 3003,
    discoveryYear: 1751,
    discoverer: 'Axel Fredrik Cronstedt',
    summary: 'Nickel is a chemical element with the symbol Ni and atomic number 28. It is a silvery-white, lustrous metal with a slight golden tinge. Nickel is a hard, ductile, ferromagnetic metal.',
    externalLink: 'https://en.wikipedia.org/wiki/Nickel',
    category: 'Transition Metal',
    electronConfiguration: [2, 8, 16, 2],
    xpos: 10,
    ypos: 4,
  },
  {
    atomicNumber: 29,
    symbol: 'Cu',
    name: 'Copper',
    atomicMass: 63.546,
    density: 8.96,
    phase: 'Solid',
    meltingPoint: 1357.77,
    boilingPoint: 2835,
    discoveryYear: 'Ancient',
    discoverer: 'Unknown',
    summary: 'Copper is a chemical element with the symbol Cu and atomic number 29. It is a soft, malleable, and ductile metal with very high thermal and electrical conductivity. A freshly exposed surface of pure copper has a reddish-orange color.',
    externalLink: 'https://en.wikipedia.org/wiki/Copper',
    category: 'Transition Metal',
    electronConfiguration: [2, 8, 18, 1],
    xpos: 11,
    ypos: 4,
  },
  {
    atomicNumber: 30,
    symbol: 'Zn',
    name: 'Zinc',
    atomicMass: 65.38,
    density: 7.14,
    phase: 'Solid',
    meltingPoint: 692.68,
    boilingPoint: 1180,
    discoveryYear: 'Ancient',
    discoverer: 'Unknown',
    summary: 'Zinc is a chemical element with the symbol Zn and atomic number 30. Zinc is a slightly brittle metal at room temperature and has a silvery-greyish appearance when oxidation is removed. It is the first element in group 12 of the periodic table.',
    externalLink: 'https://en.wikipedia.org/wiki/Zinc',
    category: 'Transition Metal',
    electronConfiguration: [2, 8, 18, 2],
    xpos: 12,
    ypos: 4,
  },
  {
    atomicNumber: 31,
    symbol: 'Ga',
    name: 'Gallium',
    atomicMass: 69.723,
    density: 5.904,
    phase: 'Solid',
    meltingPoint: 302.9146,
    boilingPoint: 2477,
    discoveryYear: 1875,
    discoverer: 'Paul-Émile Lecoq de Boisbaudran',
    summary: 'Gallium is a chemical element with the symbol Ga and atomic number 31. Elemental gallium is a soft, silvery-blue metal at standard temperature and pressure; however, it is a liquid at temperatures greater than 29.76 °C (85.57 °F), above room temperature.',
    externalLink: 'https://en.wikipedia.org/wiki/Gallium',
    category: 'Post-Transition Metal',
    electronConfiguration: [2, 8, 18, 3],
    xpos: 13,
    ypos: 4,
  },
  {
    atomicNumber: 32,
    symbol: 'Ge',
    name: 'Germanium',
    atomicMass: 72.63,
    density: 5.323,
    phase: 'Solid',
    meltingPoint: 1211.4,
    boilingPoint: 3106,
    discoveryYear: 1886,
    discoverer: 'Clemens Winkler',
    summary: 'Germanium is a chemical element with the symbol Ge and atomic number 32. It is a lustrous, hard, silvery-white metalloid in the carbon group, chemically similar to silicon and tin.',
    externalLink: 'https://en.wikipedia.org/wiki/Germanium',
    category: 'Metalloid',
    electronConfiguration: [2, 8, 18, 4],
    xpos: 14,
    ypos: 4,
  },
  {
    atomicNumber: 33,
    symbol: 'As',
    name: 'Arsenic',
    atomicMass: 74.921595,
    density: 5.727,
    phase: 'Solid',
    meltingPoint: 1090,
    boilingPoint: 887,
    discoveryYear: 'Ancient',
    discoverer: 'Albertus Magnus',
    summary: 'Arsenic is a chemical element with the symbol As and atomic number 33. Arsenic occurs in many minerals, usually in combination with sulfur and metals, but also as a pure elemental crystal. It is a metalloid.',
    externalLink: 'https://en.wikipedia.org/wiki/Arsenic',
    category: 'Metalloid',
    electronConfiguration: [2, 8, 18, 5],
    xpos: 15,
    ypos: 4,
  },
  {
    atomicNumber: 34,
    symbol: 'Se',
    name: 'Selenium',
    atomicMass: 78.971,
    density: 4.819,
    phase: 'Solid',
    meltingPoint: 494,
    boilingPoint: 958,
    discoveryYear: 1817,
    discoverer: 'Jöns Jacob Berzelius',
    summary: 'Selenium is a chemical element with the symbol Se and atomic number 34. It is a nonmetal with properties that are intermediate between those of its periodic table neighbors sulfur and tellurium.',
    externalLink: 'https://en.wikipedia.org/wiki/Selenium',
    category: 'Nonmetal',
    electronConfiguration: [2, 8, 18, 6],
    xpos: 16,
    ypos: 4,
  },
  {
    atomicNumber: 35,
    symbol: 'Br',
    name: 'Bromine',
    atomicMass: 79.904,
    density: 3.1028,
    phase: 'Liquid',
    meltingPoint: 265.8,
    boilingPoint: 332,
    discoveryYear: 1826,
    discoverer: 'Antoine Jérôme Balard',
    summary: 'Bromine is a chemical element with the symbol Br and atomic number 35. It is a halogen. The element was isolated by Antoine Jérôme Balard in 1826. Bromine is a fuming red-brown liquid at room temperature.',
    externalLink: 'https://en.wikipedia.org/wiki/Bromine',
    category: 'Nonmetal',
    electronConfiguration: [2, 8, 18, 7],
    xpos: 17,
    ypos: 4,
  },
  {
    atomicNumber: 36,
    symbol: 'Kr',
    name: 'Krypton',
    atomicMass: 83.798,
    density: 3.749,
    phase: 'Gas',
    meltingPoint: 115.78,
    boilingPoint: 119.93,
    discoveryYear: 1898,
    discoverer: 'William Ramsay, Morris Travers',
    summary: 'Krypton is a chemical element with the symbol Kr and atomic number 36. It is a member of group 18 (noble gases) elements. A colorless, odorless, tasteless noble gas, krypton occurs in trace amounts in the atmosphere, and is often used with other rare gases in fluorescent lamps.',
    externalLink: 'https://en.wikipedia.org/wiki/Krypton',
    category: 'Noble Gas',
    electronConfiguration: [2, 8, 18, 8],
    xpos: 18,
    ypos: 4,
  },
  {
    atomicNumber: 37,
    symbol: 'Rb',
    name: 'Rubidium',
    atomicMass: 85.4678,
    density: 1.532,
    phase: 'Solid',
    meltingPoint: 312.45,
    boilingPoint: 961,
    discoveryYear: 1861,
    discoverer: 'Robert Bunsen, Gustav Kirchhoff',
    summary: 'Rubidium is a chemical element with the symbol Rb and atomic number 37. Rubidium is a soft, silvery-white metallic element of the alkali metal group. Rubidium is highly reactive, with properties similar to other alkali metals, such as rapid oxidation in air.',
    externalLink: 'https://en.wikipedia.org/wiki/Rubidium',
    category: 'Alkali Metal',
    electronConfiguration: [2, 8, 18, 8, 1],
    xpos: 1,
    ypos: 5,
  },
  {
    atomicNumber: 38,
    symbol: 'Sr',
    name: 'Strontium',
    atomicMass: 87.62,
    density: 2.64,
    phase: 'Solid',
    meltingPoint: 1050,
    boilingPoint: 1655,
    discoveryYear: 1790,
    discoverer: 'Adair Crawford',
    summary: 'Strontium is a chemical element with the symbol Sr and atomic number 38. An alkaline earth metal, strontium is a soft silver-white yellowish metallic element that is highly reactive chemically. The metal forms a dark oxide layer when it is exposed to air.',
    externalLink: 'https://en.wikipedia.org/wiki/Strontium',
    category: 'Alkaline Earth Metal',
    electronConfiguration: [2, 8, 18, 8, 2],
    xpos: 2,
    ypos: 5,
  },
  {
    atomicNumber: 39,
    symbol: 'Y',
    name: 'Yttrium',
    atomicMass: 88.90584,
    density: 4.472,
    phase: 'Solid',
    meltingPoint: 1799,
    boilingPoint: 3609,
    discoveryYear: 1794,
    discoverer: 'Johan Gadolin',
    summary: 'Yttrium is a chemical element with the symbol Y and atomic number 39. It is a silvery-metallic transition metal chemically similar to the lanthanides and has often been classified as a "rare-earth element".',
    externalLink: 'https://en.wikipedia.org/wiki/Yttrium',
    category: 'Transition Metal',
    electronConfiguration: [2, 8, 18, 9, 2],
    xpos: 3,
    ypos: 5,
  },
  {
    atomicNumber: 40,
    symbol: 'Zr',
    name: 'Zirconium',
    atomicMass: 91.224,
    density: 6.511,
    phase: 'Solid',
    meltingPoint: 2128,
    boilingPoint: 4650,
    discoveryYear: 1789,
    discoverer: 'Martin Heinrich Klaproth',
    summary: 'Zirconium is a chemical element with the symbol Zr and atomic number 40. It is a lustrous, grey-white, strong transition metal that resembles titanium. Zirconium is mainly used as a refractory and opacifier, although minor amounts are used as an alloying agent for its strong resistance to corrosion.',
    externalLink: 'https://en.wikipedia.org/wiki/Zirconium',
    category: 'Transition Metal',
    electronConfiguration: [2, 8, 18, 10, 2],
    xpos: 4,
    ypos: 5,
  },
  {
    atomicNumber: 41,
    symbol: 'Nb',
    name: 'Niobium',
    atomicMass: 92.90637,
    density: 8.57,
    phase: 'Solid',
    meltingPoint: 2750,
    boilingPoint: 5017,
    discoveryYear: 1801,
    discoverer: 'Charles Hatchett',
    summary: 'Niobium is a chemical element with the symbol Nb and atomic number 41. It is a soft, grey, ductile transition metal, which is often found in the minerals pyrochlore and columbite. Niobium is used in various superconducting materials.',
    externalLink: 'https://en.wikipedia.org/wiki/Niobium',
    category: 'Transition Metal',
    electronConfiguration: [2, 8, 18, 12, 1],
    xpos: 5,
    ypos: 5,
  },
  {
    atomicNumber: 42,
    symbol: 'Mo',
    name: 'Molybdenum',
    atomicMass: 95.95,
    density: 10.28,
    phase: 'Solid',
    meltingPoint: 2896,
    boilingPoint: 4912,
    discoveryYear: 1778,
    discoverer: 'Carl Wilhelm Scheele',
    summary: 'Molybdenum is a chemical element with the symbol Mo and atomic number 42. The name is from Neo-Latin Molybdaenum, from Ancient Greek molybdos, meaning lead, as it was confused with lead ores. Molybdenum is a silvery metal with a grey tinge.',
    externalLink: 'https://en.wikipedia.org/wiki/Molybdenum',
    category: 'Transition Metal',
    electronConfiguration: [2, 8, 18, 13, 1],
    xpos: 6,
    ypos: 5,
  },
  {
    atomicNumber: 43,
    symbol: 'Tc',
    name: 'Technetium',
    atomicMass: 98,
    density: 11,
    phase: 'Solid',
    meltingPoint: 2430,
    boilingPoint: 4538,
    discoveryYear: 1937,
    discoverer: 'Emilio Segrè, Carlo Perrier',
    summary: 'Technetium is a chemical element with the symbol Tc and atomic number 43. It is the lightest element whose isotopes are all radioactive; no stable isotopes exist. It is a silvery-grey transition metal.',
    externalLink: 'https://en.wikipedia.org/wiki/Technetium',
    category: 'Transition Metal',
    electronConfiguration: [2, 8, 18, 13, 2],
    xpos: 7,
    ypos: 5,
  },
  {
    atomicNumber: 44,
    symbol: 'Ru',
    name: 'Ruthenium',
    atomicMass: 101.07,
    density: 12.45,
    phase: 'Solid',
    meltingPoint: 2607,
    boilingPoint: 4423,
    discoveryYear: 1844,
    discoverer: 'Karl Ernst Claus',
    summary: 'Ruthenium is a chemical element with the symbol Ru and atomic number 44. It is a rare transition metal belonging to the platinum group of the periodic table. Like the other metals of the platinum group, ruthenium is inert to most other chemicals.',
    externalLink: 'https://en.wikipedia.org/wiki/Ruthenium',
    category: 'Transition Metal',
    electronConfiguration: [2, 8, 18, 15, 1],
    xpos: 8,
    ypos: 5,
  },
  {
    atomicNumber: 45,
    symbol: 'Rh',
    name: 'Rhodium',
    atomicMass: 102.90550,
    density: 12.41,
    phase: 'Solid',
    meltingPoint: 2237,
    boilingPoint: 3968,
    discoveryYear: 1803,
    discoverer: 'William Hyde Wollaston',
    summary: 'Rhodium is a chemical element with the symbol Rh and atomic number 45. It is a rare, silvery-white, hard, corrosion-resistant, and chemically inert transition metal. It is a member of the platinum group metals.',
    externalLink: 'https://en.wikipedia.org/wiki/Rhodium',
    category: 'Transition Metal',
    electronConfiguration: [2, 8, 18, 16, 1],
    xpos: 9,
    ypos: 5,
  },
  {
    atomicNumber: 46,
    symbol: 'Pd',
    name: 'Palladium',
    atomicMass: 106.42,
    density: 12.023,
    phase: 'Solid',
    meltingPoint: 1828.05,
    boilingPoint: 3236,
    discoveryYear: 1803,
    discoverer: 'William Hyde Wollaston',
    summary: 'Palladium is a chemical element with the symbol Pd and atomic number 46. It is a rare and lustrous silvery-white metal. It is a member of the platinum group metals.',
    externalLink: 'https://en.wikipedia.org/wiki/Palladium',
    category: 'Transition Metal',
    electronConfiguration: [2, 8, 18, 18, 0],
    xpos: 10,
    ypos: 5,
  },
  {
    atomicNumber: 47,
    symbol: 'Ag',
    name: 'Silver',
    atomicMass: 107.8682,
    density: 10.49,
    phase: 'Solid',
    meltingPoint: 1234.93,
    boilingPoint: 2435,
    discoveryYear: 'Ancient',
    discoverer: 'Unknown',
    summary: 'Silver is a chemical element with the symbol Ag and atomic number 47. A soft, white, lustrous transition metal, it exhibits the highest electrical conductivity, thermal conductivity, and reflectivity of any metal.',
    externalLink: 'https://en.wikipedia.org/wiki/Silver',
    category: 'Transition Metal',
    electronConfiguration: [2, 8, 18, 18, 1],
    xpos: 11,
    ypos: 5,
  },
  {
    atomicNumber: 48,
    symbol: 'Cd',
    name: 'Cadmium',
    atomicMass: 112.414,
    density: 8.65,
    phase: 'Solid',
    meltingPoint: 594.22,
    boilingPoint: 1040,
    discoveryYear: 1817,
    discoverer: 'Karl Samuel Leberecht Hermann, Friedrich Stromeyer',
    summary: 'Cadmium is a chemical element with the symbol Cd and atomic number 48. This soft, silvery-white metal is chemically similar to the other two metals in group 12, zinc and mercury.',
    externalLink: 'https://en.wikipedia.org/wiki/Cadmium',
    category: 'Transition Metal',
    electronConfiguration: [2, 8, 18, 18, 2],
    xpos: 12,
    ypos: 5,
  },
  {
    atomicNumber: 49,
    symbol: 'In',
    name: 'Indium',
    atomicMass: 114.818,
    density: 7.31,
    phase: 'Solid',
    meltingPoint: 429.7485,
    boilingPoint: 2345,
    discoveryYear: 1863,
    discoverer: 'Ferdinand Reich, Hieronymus Theodor Richter',
    summary: 'Indium is a chemical element with the symbol In and atomic number 49. Indium is a soft, malleable, easily fusible post-transition metal. It is a silvery-white metal with a bright luster.',
    externalLink: 'https://en.wikipedia.org/wiki/Indium',
    category: 'Post-Transition Metal',
    electronConfiguration: [2, 8, 18, 18, 3],
    xpos: 13,
    ypos: 5,
  },
  {
    atomicNumber: 50,
    symbol: 'Sn',
    name: 'Tin',
    atomicMass: 118.710,
    density: 7.265,
    phase: 'Solid',
    meltingPoint: 505.08,
    boilingPoint: 2875,
    discoveryYear: 'Ancient',
    discoverer: 'Unknown',
    summary: 'Tin is a chemical element with the symbol Sn and atomic number 50. Tin is a malleable, ductile, highly crystalline silvery-white metal. When a bar of tin is bent, the so-called "tin cry" can be heard due to the twinning of the crystals.',
    externalLink: 'https://en.wikipedia.org/wiki/Tin',
    category: 'Post-Transition Metal',
    electronConfiguration: [2, 8, 18, 18, 4],
    xpos: 14,
    ypos: 5,
  },
  {
    atomicNumber: 51,
    symbol: 'Sb',
    name: 'Antimony',
    atomicMass: 121.760,
    density: 6.697,
    phase: 'Solid',
    meltingPoint: 903.78,
    boilingPoint: 1860,
    discoveryYear: 'Ancient',
    discoverer: 'Unknown',
    summary: 'Antimony is a chemical element with the symbol Sb and atomic number 51. A lustrous gray metalloid, it is found in nature mainly as the sulfide mineral stibnite (Sb2S3). Antimony compounds have been known since ancient times and were powdered for use as medicine and cosmetics.',
    externalLink: 'https://en.wikipedia.org/wiki/Antimony',
    category: 'Metalloid',
    electronConfiguration: [2, 8, 18, 18, 5],
    xpos: 15,
    ypos: 5,
  },
  {
    atomicNumber: 52,
    symbol: 'Te',
    name: 'Tellurium',
    atomicMass: 127.60,
    density: 6.24,
    phase: 'Solid',
    meltingPoint: 722.66,
    boilingPoint: 1261,
    discoveryYear: 1782,
    discoverer: 'Franz-Joseph Müller von Reichenstein',
    summary: 'Tellurium is a chemical element with the symbol Te and atomic number 52. It is a brittle, mildly toxic, rare, silver-white metalloid. Tellurium is chemically related to selenium and sulfur.',
    externalLink: 'https://en.wikipedia.org/wiki/Tellurium',
    category: 'Metalloid',
    electronConfiguration: [2, 8, 18, 18, 6],
    xpos: 16,
    ypos: 5,
  },
  {
    atomicNumber: 53,
    symbol: 'I',
    name: 'Iodine',
    atomicMass: 126.90447,
    density: 4.933,
    phase: 'Solid',
    meltingPoint: 386.85,
    boilingPoint: 457.4,
    discoveryYear: 1811,
    discoverer: 'Bernard Courtois',
    summary: 'Iodine is a chemical element with the symbol I and atomic number 53. The heaviest of the stable halogens, it exists as a semi-lustrous, non-metallic solid at standard conditions that sublimes readily to form a violet gas.',
    externalLink: 'https://en.wikipedia.org/wiki/Iodine',
    category: 'Nonmetal',
    electronConfiguration: [2, 8, 18, 18, 7],
    xpos: 17,
    ypos: 5,
  },
  {
    atomicNumber: 54,
    symbol: 'Xe',
    name: 'Xenon',
    atomicMass: 131.293,
    density: 5.894,
    phase: 'Gas',
    meltingPoint: 161.3,
    boilingPoint: 165.051,
    discoveryYear: 1898,
    discoverer: 'William Ramsay, Morris Travers',
    summary: 'Xenon is a chemical element with the symbol Xe and atomic number 54. It is a colorless, dense, odorless noble gas found in the Earth\'s atmosphere in trace amounts. Although generally unreactive, xenon can undergo a few chemical reactions such as the formation of xenon hexafluoroplatinate, the first noble gas compound to be synthesized.',
    externalLink: 'https://en.wikipedia.org/wiki/Xenon',
    category: 'Noble Gas',
    electronConfiguration: [2, 8, 18, 18, 8],
    xpos: 18,
    ypos: 5,
  },
  {
    atomicNumber: 55,
    symbol: 'Cs',
    name: 'Cesium',
    atomicMass: 132.90545196,
    density: 1.879,
    phase: 'Solid',
    meltingPoint: 301.59,
    boilingPoint: 944,
    discoveryYear: 1860,
    discoverer: 'Robert Bunsen, Gustav Kirchhoff',
    summary: 'Caesium is a chemical element with the symbol Cs and atomic number 55. It is a soft, silvery-gold alkali metal with a melting point of 28.5 °C (83.3 °F), which makes it one of only five elemental metals that are liquid at or near room temperature.',
    externalLink: 'https://en.wikipedia.org/wiki/Caesium',
    category: 'Alkali Metal',
    electronConfiguration: [2, 8, 18, 18, 8, 1],
    xpos: 1,
    ypos: 6,
  },
  {
    atomicNumber: 56,
    symbol: 'Ba',
    name: 'Barium',
    atomicMass: 137.327,
    density: 3.51,
    phase: 'Solid',
    meltingPoint: 1000,
    boilingPoint: 2170,
    discoveryYear: 1808,
    discoverer: 'Humphry Davy',
    summary: 'Barium is a chemical element with the symbol Ba and atomic number 56. It is the fifth element in Group 2, a soft silvery alkaline earth metal. Because of its high chemical reactivity, barium is never found in nature as a free element.',
    externalLink: 'https://en.wikipedia.org/wiki/Barium',
    category: 'Alkaline Earth Metal',
    electronConfiguration: [2, 8, 18, 18, 8, 2],
    xpos: 2,
    ypos: 6,
  },
  {
    atomicNumber: 57,
    symbol: 'La',
    name: 'Lanthanum',
    atomicMass: 138.90547,
    density: 6.162,
    phase: 'Solid',
    meltingPoint: 1193,
    boilingPoint: 3737,
    discoveryYear: 1839,
    discoverer: 'Carl Gustaf Mosander',
    summary: 'Lanthanum is a chemical element with the symbol La and atomic number 57. It is a soft, ductile, silvery-white metallic chemical element. It is the first element of the lanthanide series.',
    externalLink: 'https://en.wikipedia.org/wiki/Lanthanum',
    category: 'Lanthanide',
    electronConfiguration: [2, 8, 18, 18, 9, 2],
    xpos: 3,
    ypos: 9, // Placeholder for Lanthanides
  },
  {
    atomicNumber: 58,
    symbol: 'Ce',
    name: 'Cerium',
    atomicMass: 140.116,
    density: 6.77,
    phase: 'Solid',
    meltingPoint: 1068,
    boilingPoint: 3716,
    discoveryYear: 1803,
    discoverer: 'Jöns Jacob Berzelius, Wilhelm Hisinger, Martin Heinrich Klaproth',
    summary: 'Cerium is a chemical element with the symbol Ce and atomic number 58. Cerium is a soft, ductile, silvery-white metal that tarnishes when exposed to air, and it is soft enough to be cut with a knife.',
    externalLink: 'https://en.wikipedia.org/wiki/Cerium',
    category: 'Lanthanide',
    electronConfiguration: [2, 8, 18, 19, 9, 2],
    xpos: 4,
    ypos: 9,
  },
  {
    atomicNumber: 59,
    symbol: 'Pr',
    name: 'Praseodymium',
    atomicMass: 140.90766,
    density: 6.77,
    phase: 'Solid',
    meltingPoint: 1208,
    boilingPoint: 3793,
    discoveryYear: 1885,
    discoverer: 'Carl Auer von Welsbach',
    summary: 'Praseodymium is a chemical element with the symbol Pr and atomic number 59. It is a soft, silvery, malleable and ductile metal in the lanthanide group. It is valued for its magnetic, electrical, chemical, and optical properties.',
    externalLink: 'https://en.wikipedia.org/wiki/Praseodymium',
    category: 'Lanthanide',
    electronConfiguration: [2, 8, 18, 21, 8, 2],
    xpos: 5,
    ypos: 9,
  },
  {
    atomicNumber: 60,
    symbol: 'Nd',
    name: 'Neodymium',
    atomicMass: 144.242,
    density: 7.01,
    phase: 'Solid',
    meltingPoint: 1297,
    boilingPoint: 3347,
    discoveryYear: 1885,
    discoverer: 'Carl Auer von Welsbach',
    summary: 'Neodymium is a chemical element with the symbol Nd and atomic number 60. It is a soft, silvery metal that tarnishes in air and moisture. Neodymium is used in magnets, lasers, and as a coloring agent in glass.',
    externalLink: 'https://en.wikipedia.org/wiki/Neodymium',
    category: 'Lanthanide',
    electronConfiguration: [2, 8, 18, 22, 8, 2],
    xpos: 6,
    ypos: 9,
  },
  {
    atomicNumber: 61,
    symbol: 'Pm',
    name: 'Promethium',
    atomicMass: 145,
    density: 7.26,
    phase: 'Solid',
    meltingPoint: 1315,
    boilingPoint: 3273,
    discoveryYear: 1945,
    discoverer: 'Jacob A. Marinsky, Lawrence E. Glendenin, Charles D. Coryell',
    summary: 'Promethium is a chemical element with the symbol Pm and atomic number 61. All of its isotopes are radioactive; it is the only element with no stable isotopes that is followed by stable elements in the periodic table. Promethium is a soft beta emitter.',
    externalLink: 'https://en.wikipedia.org/wiki/Promethium',
    category: 'Lanthanide',
    electronConfiguration: [2, 8, 18, 23, 8, 2],
    xpos: 7,
    ypos: 9,
  },
  {
    atomicNumber: 62,
    symbol: 'Sm',
    name: 'Samarium',
    atomicMass: 150.36,
    density: 7.52,
    phase: 'Solid',
    meltingPoint: 1345,
    boilingPoint: 2067,
    discoveryYear: 1879,
    discoverer: 'Paul-Émile Lecoq de Boisbaudran',
    summary: 'Samarium is a chemical element with the symbol Sm and atomic number 62. It is a silvery-white metal that is a member of the lanthanide series. Samarium is relatively stable in air, but it reacts with water and acids.',
    externalLink: 'https://en.wikipedia.org/wiki/Samarium',
    category: 'Lanthanide',
    electronConfiguration: [2, 8, 18, 24, 8, 2],
    xpos: 8,
    ypos: 9,
  },
  {
    atomicNumber: 63,
    symbol: 'Eu',
    name: 'Europium',
    atomicMass: 151.964,
    density: 5.244,
    phase: 'Solid',
    meltingPoint: 1099,
    boilingPoint: 1802,
    discoveryYear: 1901,
    discoverer: 'Eugène-Anatole Demarçay',
    summary: 'Europium is a chemical element with the symbol Eu and atomic number 63. It is a soft, silvery metal that is easily oxidized in air and water. Europium is the most reactive of the lanthanide elements.',
    externalLink: 'https://en.wikipedia.org/wiki/Europium',
    category: 'Lanthanide',
    electronConfiguration: [2, 8, 18, 25, 8, 2],
    xpos: 9,
    ypos: 9,
  },
  {
    atomicNumber: 64,
    symbol: 'Gd',
    name: 'Gadolinium',
    atomicMass: 157.25,
    density: 7.9,
    phase: 'Solid',
    meltingPoint: 1586,
    boilingPoint: 3573,
    discoveryYear: 1886,
    discoverer: 'Jean Charles Galissard de Marignac',
    summary: 'Gadolinium is a chemical element with the symbol Gd and atomic number 64. It is a silvery-white, malleable, and ductile rare-earth metal. Gadolinium is ferromagnetic at room temperature.',
    externalLink: 'https://en.wikipedia.org/wiki/Gadolinium',
    category: 'Lanthanide',
    electronConfiguration: [2, 8, 18, 25, 9, 2],
    xpos: 10,
    ypos: 9,
  },
  {
    atomicNumber: 65,
    symbol: 'Tb',
    name: 'Terbium',
    atomicMass: 158.92535,
    density: 8.23,
    phase: 'Solid',
    meltingPoint: 1629,
    boilingPoint: 3396,
    discoveryYear: 1843,
    discoverer: 'Carl Gustaf Mosander',
    summary: 'Terbium is a chemical element with the symbol Tb and atomic number 65. It is a silvery-white, rare-earth metal that is malleable, ductile, and soft enough to be cut with a knife. Terbium is used in alloys and in some electronic devices.',
    externalLink: 'https://en.wikipedia.org/wiki/Terbium',
    category: 'Lanthanide',
    electronConfiguration: [2, 8, 18, 27, 8, 2],
    xpos: 11,
    ypos: 9,
  },
  {
    atomicNumber: 66,
    symbol: 'Dy',
    name: 'Dysprosium',
    atomicMass: 162.500,
    density: 8.54,
    phase: 'Solid',
    meltingPoint: 1680,
    boilingPoint: 2840,
    discoveryYear: 1886,
    discoverer: 'Paul-Émile Lecoq de Boisbaudran',
    summary: 'Dysprosium is a chemical element with the symbol Dy and atomic number 66. It is a rare-earth element with a metallic, silvery luster. Dysprosium is relatively stable in air, but it reacts with water and acids.',
    externalLink: 'https://en.wikipedia.org/wiki/Dysprosium',
    category: 'Lanthanide',
    electronConfiguration: [2, 8, 18, 28, 8, 2],
    xpos: 12,
    ypos: 9,
  },
  {
    atomicNumber: 67,
    symbol: 'Ho',
    name: 'Holmium',
    atomicMass: 164.93033,
    density: 8.79,
    phase: 'Solid',
    meltingPoint: 1734,
    boilingPoint: 2873,
    discoveryYear: 1878,
    discoverer: 'Marc Delafontaine, Jacques-Louis Soret, Per Teodor Cleve',
    summary: 'Holmium is a chemical element with the symbol Ho and atomic number 67. It is a rare-earth element and is a relatively soft, malleable, silvery-white metal. Holmium is used in some specialized alloys and as a coloring agent in glass.',
    externalLink: 'https://en.wikipedia.org/wiki/Holmium',
    category: 'Lanthanide',
    electronConfiguration: [2, 8, 18, 29, 8, 2],
    xpos: 13,
    ypos: 9,
  },
  {
    atomicNumber: 68,
    symbol: 'Er',
    name: 'Erbium',
    atomicMass: 167.259,
    density: 9.066,
    phase: 'Solid',
    meltingPoint: 1802,
    boilingPoint: 3141,
    discoveryYear: 1843,
    discoverer: 'Carl Gustaf Mosander',
    summary: 'Erbium is a chemical element with the symbol Er and atomic number 68. It is a soft, malleable, silvery-white metal that is a member of the lanthanide series. Erbium is used in some specialized alloys and as a coloring agent in glass.',
    externalLink: 'https://en.wikipedia.org/wiki/Erbium',
    category: 'Lanthanide',
    electronConfiguration: [2, 8, 18, 30, 8, 2],
    xpos: 14,
    ypos: 9,
  },
  {
    atomicNumber: 69,
    symbol: 'Tm',
    name: 'Thulium',
    atomicMass: 168.93422,
    density: 9.32,
    phase: 'Solid',
    meltingPoint: 1818,
    boilingPoint: 2223,
    discoveryYear: 1879,
    discoverer: 'Per Teodor Cleve',
    summary: 'Thulium is a chemical element with the symbol Tm and atomic number 69. It is the second least abundant of the lanthanides. It is a soft, malleable, silvery-gray metal.',
    externalLink: 'https://en.wikipedia.org/wiki/Thulium',
    category: 'Lanthanide',
    electronConfiguration: [2, 8, 18, 31, 8, 2],
    xpos: 15,
    ypos: 9,
  },
  {
    atomicNumber: 70,
    symbol: 'Yb',
    name: 'Ytterbium',
    atomicMass: 173.045,
    density: 6.9,
    phase: 'Solid',
    meltingPoint: 1097,
    boilingPoint: 1469,
    discoveryYear: 1878,
    discoverer: 'Jean Charles Galissard de Marignac',
    summary: 'Ytterbium is a chemical element with the symbol Yb and atomic number 70. It is a soft, malleable, and ductile silvery-white metal. Ytterbium is used in some specialized alloys and in some electronic devices.',
    externalLink: 'https://en.wikipedia.org/wiki/Ytterbium',
    category: 'Lanthanide',
    electronConfiguration: [2, 8, 18, 32, 8, 2],
    xpos: 16,
    ypos: 9,
  },
  {
    atomicNumber: 71,
    symbol: 'Lu',
    name: 'Lutetium',
    atomicMass: 174.9668,
    density: 9.84,
    phase: 'Solid',
    meltingPoint: 1925,
    boilingPoint: 3675,
    discoveryYear: 1907,
    discoverer: 'Georges Urbain, Carl Auer von Welsbach, Charles James',
    summary: 'Lutetium is a chemical element with the symbol Lu and atomic number 71. It is a silvery-white metal, which resists corrosion in dry air, but not in moist air. Lutetium is the last element in the lanthanide series.',
    externalLink: 'https://en.wikipedia.org/wiki/Lutetium',
    category: 'Lanthanide',
    electronConfiguration: [2, 8, 18, 32, 9, 2],
    xpos: 17,
    ypos: 9,
  },
  {
    atomicNumber: 72,
    symbol: 'Hf',
    name: 'Hafnium',
    atomicMass: 178.49,
    density: 13.31,
    phase: 'Solid',
    meltingPoint: 2506,
    boilingPoint: 4876,
    discoveryYear: 1923,
    discoverer: 'Dirk Coster, George de Hevesy',
    summary: 'Hafnium is a chemical element with the symbol Hf and atomic number 72. A lustrous, silvery, ductile transition metal, hafnium is chemically similar to zirconium and is found in zirconium minerals.',
    externalLink: 'https://en.wikipedia.org/wiki/Hafnium',
    category: 'Transition Metal',
    electronConfiguration: [2, 8, 18, 32, 10, 2],
    xpos: 4,
    ypos: 6,
  },
  {
    atomicNumber: 73,
    symbol: 'Ta',
    name: 'Tantalum',
    atomicMass: 180.94788,
    density: 16.69,
    phase: 'Solid',
    meltingPoint: 3290,
    boilingPoint: 5731,
    discoveryYear: 1802,
    discoverer: 'Anders Gustaf Ekeberg',
    summary: 'Tantalum is a chemical element with the symbol Ta and atomic number 73. It is a rare, hard, blue-gray, lustrous transition metal that is highly corrosion-resistant. Tantalum is part of the refractory metals group, which are widely used as minor components in alloys.',
    externalLink: 'https://en.wikipedia.org/wiki/Tantalum',
    category: 'Transition Metal',
    electronConfiguration: [2, 8, 18, 32, 11, 2],
    xpos: 5,
    ypos: 6,
  },
  {
    atomicNumber: 74,
    symbol: 'W',
    name: 'Tungsten',
    atomicMass: 183.84,
    density: 19.25,
    phase: 'Solid',
    meltingPoint: 3695,
    boilingPoint: 6203,
    discoveryYear: 1781,
    discoverer: 'Carl Wilhelm Scheele, Juan José Elhuyar, Fausto Elhuyar',
    summary: 'Tungsten is a chemical element with the symbol W and atomic number 74. The name tungsten comes from the Swedish language tung sten, which means "heavy stone". Tungsten is a rare metal found naturally on Earth almost exclusively in chemical compounds rather than as a free element.',
    externalLink: 'https://en.wikipedia.org/wiki/Tungsten',
    category: 'Transition Metal',
    electronConfiguration: [2, 8, 18, 32, 12, 2],
    xpos: 6,
    ypos: 6,
  },
  {
    atomicNumber: 75,
    symbol: 'Re',
    name: 'Rhenium',
    atomicMass: 186.207,
    density: 21.02,
    phase: 'Solid',
    meltingPoint: 3459,
    boilingPoint: 5869,
    discoveryYear: 1925,
    discoverer: 'Walter Noddack, Ida Noddack, Otto Berg',
    summary: 'Rhenium is a chemical element with the symbol Re and atomic number 75. It is a silvery-white, heavy, third-row transition metal in Group 7 of the periodic table. Rhenium is one of the rarest elements in the Earth\'s crust.',
    externalLink: 'https://en.wikipedia.org/wiki/Rhenium',
    category: 'Transition Metal',
    electronConfiguration: [2, 8, 18, 32, 13, 2],
    xpos: 7,
    ypos: 6,
  },
  {
    atomicNumber: 76,
    symbol: 'Os',
    name: 'Osmium',
    atomicMass: 190.23,
    density: 22.59,
    phase: 'Solid',
    meltingPoint: 3306,
    boilingPoint: 5285,
    discoveryYear: 1803,
    discoverer: 'Smithson Tennant',
    summary: 'Osmium is a chemical element with the symbol Os and atomic number 76. It is a hard, brittle, silvery-blue transition metal in the platinum group. Osmium is the densest naturally occurring element.',
    externalLink: 'https://en.wikipedia.org/wiki/Osmium',
    category: 'Transition Metal',
    electronConfiguration: [2, 8, 18, 32, 14, 2],
    xpos: 8,
    ypos: 6,
  },
  {
    atomicNumber: 77,
    symbol: 'Ir',
    name: 'Iridium',
    atomicMass: 192.217,
    density: 22.56,
    phase: 'Solid',
    meltingPoint: 2719,
    boilingPoint: 4701,
    discoveryYear: 1803,
    discoverer: 'Smithson Tennant',
    summary: 'Iridium is a chemical element with the symbol Ir and atomic number 77. A very hard, brittle, silvery-white transition metal of the platinum group, it is the second-densest naturally occurring element (after osmium).',
    externalLink: 'https://en.wikipedia.org/wiki/Iridium',
    category: 'Transition Metal',
    electronConfiguration: [2, 8, 18, 32, 15, 2],
    xpos: 9,
    ypos: 6,
  },
  {
    atomicNumber: 78,
    symbol: 'Pt',
    name: 'Platinum',
    atomicMass: 195.084,
    density: 21.45,
    phase: 'Solid',
    meltingPoint: 2041.4,
    boilingPoint: 4098,
    discoveryYear: 1735,
    discoverer: 'Antonio de Ulloa',
    summary: 'Platinum is a chemical element with the symbol Pt and atomic number 78. It is a dense, malleable, ductile, highly unreactive, silvery-white transition metal. Its name is derived from the Spanish term platino, meaning "little silver".',
    externalLink: 'https://en.wikipedia.org/wiki/Platinum',
    category: 'Transition Metal',
    electronConfiguration: [2, 8, 18, 32, 17, 1],
    xpos: 10,
    ypos: 6,
  },
  {
    atomicNumber: 79,
    symbol: 'Au',
    name: 'Gold',
    atomicMass: 196.966570,
    density: 19.3,
    phase: 'Solid',
    meltingPoint: 1337.33,
    boilingPoint: 3129,
    discoveryYear: 'Ancient',
    discoverer: 'Unknown',
    summary: 'Gold is a chemical element with the symbol Au and atomic number 79. In its purest form, it is a bright, slightly reddish yellow, dense, soft, malleable, and ductile metal. Chemically, gold is a transition metal and a group 11 element.',
    externalLink: 'https://en.wikipedia.org/wiki/Gold',
    category: 'Transition Metal',
    electronConfiguration: [2, 8, 18, 32, 18, 1],
    xpos: 11,
    ypos: 6,
  },
  {
    atomicNumber: 80,
    symbol: 'Hg',
    name: 'Mercury',
    atomicMass: 200.592,
    density: 13.534,
    phase: 'Liquid',
    meltingPoint: 234.321,
    boilingPoint: 629.88,
    discoveryYear: 'Ancient',
    discoverer: 'Unknown',
    summary: 'Mercury is a chemical element with the symbol Hg and atomic number 80. It is commonly known as quicksilver and was formerly named hydrargyrum. A heavy, silvery d-block element, mercury is the only metallic element that is liquid at standard conditions for temperature and pressure.',
    externalLink: 'https://en.wikipedia.org/wiki/Mercury',
    category: 'Transition Metal',
    electronConfiguration: [2, 8, 18, 32, 18, 2],
    xpos: 12,
    ypos: 6,
  },
  {
    atomicNumber: 81,
    symbol: 'Tl',
    name: 'Thallium',
    atomicMass: 204.38,
    density: 11.85,
    phase: 'Solid',
    meltingPoint: 577,
    boilingPoint: 1746,
    discoveryYear: 1861,
    discoverer: 'William Crookes',
    summary: 'Thallium is a chemical element with the symbol Tl and atomic number 81. This soft, malleable post-transition metal is not found free in nature. When isolated, it resembles tin, but discolors when exposed to air.',
    externalLink: 'https://en.wikipedia.org/wiki/Thallium',
    category: 'Post-Transition Metal',
    electronConfiguration: [2, 8, 18, 32, 18, 3],
    xpos: 13,
    ypos: 6,
  },
  {
    atomicNumber: 82,
    symbol: 'Pb',
    name: 'Lead',
    atomicMass: 207.2,
    density: 11.34,
    phase: 'Solid',
    meltingPoint: 600.61,
    boilingPoint: 2022,
    discoveryYear: 'Ancient',
    discoverer: 'Unknown',
    summary: 'Lead is a chemical element with the symbol Pb and atomic number 82. It is a heavy metal that is denser than most common materials. Lead is soft and malleable, and also has a relatively low melting point.',
    externalLink: 'https://en.wikipedia.org/wiki/Lead',
    category: 'Post-Transition Metal',
    electronConfiguration: [2, 8, 18, 32, 18, 4],
    xpos: 14,
    ypos: 6,
  },
  {
    atomicNumber: 83,
    symbol: 'Bi',
    name: 'Bismuth',
    atomicMass: 208.98040,
    density: 9.78,
    phase: 'Solid',
    meltingPoint: 544.7,
    boilingPoint: 1837,
    discoveryYear: 1753,
    discoverer: 'Claude François Geoffroy',
    summary: 'Bismuth is a chemical element with the symbol Bi and atomic number 83. It is a post-transition metal and one of the pnictogens with chemical properties resembling its lighter homologs arsenic and antimony. Elemental bismuth may occur naturally, and its sulfide and oxide forms are important commercial ores.',
    externalLink: 'https://en.wikipedia.org/wiki/Bismuth',
    category: 'Post-Transition Metal',
    electronConfiguration: [2, 8, 18, 32, 18, 5],
    xpos: 15,
    ypos: 6,
  },
  {
    atomicNumber: 84,
    symbol: 'Po',
    name: 'Polonium',
    atomicMass: 209,
    density: 9.196,
    phase: 'Solid',
    meltingPoint: 527,
    boilingPoint: 1237,
    discoveryYear: 1898,
    discoverer: 'Marie Curie, Pierre Curie',
    summary: 'Polonium is a chemical element with the symbol Po and atomic number 84. A rare and highly radioactive metal with no stable isotopes, polonium is chemically similar to tellurium and bismuth, and it occurs in uranium ores.',
    externalLink: 'https://en.wikipedia.org/wiki/Polonium',
    category: 'Metalloid',
    electronConfiguration: [2, 8, 18, 32, 18, 6],
    xpos: 16,
    ypos: 6,
  },
  {
    atomicNumber: 85,
    symbol: 'At',
    name: 'Astatine',
    atomicMass: 210,
    density: 6.35,
    phase: 'Solid',
    meltingPoint: 575,
    boilingPoint: 610,
    discoveryYear: 1940,
    discoverer: 'Dale R. Corson, Kenneth Ross MacKenzie, Emilio Segrè',
    summary: 'Astatine is a chemical element with the symbol At and atomic number 85. It is the rarest naturally occurring element in the Earth\'s crust, occurring only as the decay product of various heavier elements. All of its isotopes are short-lived; the most stable is astatine-210, with a half-life of 8.1 hours.',
    externalLink: 'https://en.wikipedia.org/wiki/Astatine',
    category: 'Metalloid',
    electronConfiguration: [2, 8, 18, 32, 18, 7],
    xpos: 17,
    ypos: 6,
  },
  {
    atomicNumber: 86,
    symbol: 'Rn',
    name: 'Radon',
    atomicMass: 222,
    density: 9.73,
    phase: 'Gas',
    meltingPoint: 202,
    boilingPoint: 211.3,
    discoveryYear: 1900,
    discoverer: 'Friedrich Ernst Dorn',
    summary: 'Radon is a chemical element with the symbol Rn and atomic number 86. It is a radioactive, colorless, odorless, tasteless noble gas. It is one of the densest substances that remains a gas at standard conditions.',
    externalLink: 'https://en.wikipedia.org/wiki/Radon',
    category: 'Noble Gas',
    electronConfiguration: [2, 8, 18, 32, 18, 8],
    xpos: 18,
    ypos: 6,
  },
  {
    atomicNumber: 87,
    symbol: 'Fr',
    name: 'Francium',
    atomicMass: 223,
    density: 1.87,
    phase: 'Solid',
    meltingPoint: 300,
    boilingPoint: 950,
    discoveryYear: 1939,
    discoverer: 'Marguerite Perey',
    summary: 'Francium is a chemical element with the symbol Fr and atomic number 87. It is a highly radioactive metal that decays into astatine, radium, and radon. It is the second-most electropositive element, after caesium, and is the least abundant naturally occurring element.',
    externalLink: 'https://en.wikipedia.org/wiki/Francium',
    category: 'Alkali Metal',
    electronConfiguration: [2, 8, 18, 32, 18, 8, 1],
    xpos: 1,
    ypos: 7,
  },
  {
    atomicNumber: 88,
    symbol: 'Ra',
    name: 'Radium',
    atomicMass: 226,
    density: 5.5,
    phase: 'Solid',
    meltingPoint: 973,
    boilingPoint: 2010,
    discoveryYear: 1898,
    discoverer: 'Marie Curie, Pierre Curie',
    summary: 'Radium is a chemical element with the symbol Ra and atomic number 88. It is the sixth element in Group 2 of the periodic table, also known as the alkaline earth metals. Pure radium is a silvery-white metal, but it readily oxidizes on exposure to air, turning black.',
    externalLink: 'https://en.wikipedia.org/wiki/Radium',
    category: 'Alkaline Earth Metal',
    electronConfiguration: [2, 8, 18, 32, 18, 8, 2],
    xpos: 2,
    ypos: 7,
  },
  {
    atomicNumber: 89,
    symbol: 'Ac',
    name: 'Actinium',
    atomicMass: 227,
    density: 10.07,
    phase: 'Solid',
    meltingPoint: 1323,
    boilingPoint: 3473,
    discoveryYear: 1899,
    discoverer: 'André-Louis Debierne',
    summary: 'Actinium is a chemical element with the symbol Ac and atomic number 89. It is a soft, silvery-white radioactive metallic element. It is the first element of the actinide series.',
    externalLink: 'https://en.wikipedia.org/wiki/Actinium',
    category: 'Actinide',
    electronConfiguration: [2, 8, 18, 32, 18, 9, 2],
    xpos: 3,
    ypos: 10, // Placeholder for Actinides
  },
  {
    atomicNumber: 90,
    symbol: 'Th',
    name: 'Thorium',
    atomicMass: 232.0377,
    density: 11.72,
    phase: 'Solid',
    meltingPoint: 2023,
    boilingPoint: 5061,
    discoveryYear: 1828,
    discoverer: 'Jöns Jacob Berzelius',
    summary: 'Thorium is a chemical element with the symbol Th and atomic number 90. A radioactive actinide metal, thorium is one of only two significantly radioactive elements that still occur naturally in large quantities as a primordial element (the other being uranium).',
    externalLink: 'https://en.wikipedia.org/wiki/Thorium',
    category: 'Actinide',
    electronConfiguration: [2, 8, 18, 32, 18, 10, 2],
    xpos: 4,
    ypos: 10,
  },
  {
    atomicNumber: 91,
    symbol: 'Pa',
    name: 'Protactinium',
    atomicMass: 231.03588,
    density: 15.37,
    phase: 'Solid',
    meltingPoint: 1845,
    boilingPoint: 4300,
    discoveryYear: 1913,
    discoverer: 'Kasimir Fajans, Oswald Helmuth Göhring',
    summary: 'Protactinium is a chemical element with the symbol Pa and atomic number 91. It is a dense, silvery-gray actinide metal which readily reacts with oxygen, water vapor and inorganic acids. It is one of the rarest and most expensive naturally occurring elements.',
    externalLink: 'https://en.wikipedia.org/wiki/Protactinium',
    category: 'Actinide',
    electronConfiguration: [2, 8, 18, 32, 20, 9, 2],
    xpos: 5,
    ypos: 10,
  },
  {
    atomicNumber: 92,
    symbol: 'U',
    name: 'Uranium',
    atomicMass: 238.02891,
    density: 19.1,
    phase: 'Solid',
    meltingPoint: 1405.3,
    boilingPoint: 4404,
    discoveryYear: 1789,
    discoverer: 'Martin Heinrich Klaproth',
    summary: 'Uranium is a chemical element with the symbol U and atomic number 92. It is a silvery-white metal in the actinide series of the periodic table. A uranium atom has 92 protons and 92 electrons, of which 6 are valence electrons.',
    externalLink: 'https://en.wikipedia.org/wiki/Uranium',
    category: 'Actinide',
    electronConfiguration: [2, 8, 18, 32, 21, 9, 2],
    xpos: 6,
    ypos: 10,
  },
  {
    atomicNumber: 93,
    symbol: 'Np',
    name: 'Neptunium',
    atomicMass: 237,
    density: 20.45,
    phase: 'Solid',
    meltingPoint: 917,
    boilingPoint: 4273,
    discoveryYear: 1940,
    discoverer: 'Edwin McMillan, Philip H. Abelson',
    summary: 'Neptunium is a chemical element with the symbol Np and atomic number 93. A radioactive actinide metal, neptunium is the first transuranic element. Its most stable isotope, neptunium-237, is a by-product of nuclear reactors and plutonium production.',
    externalLink: 'https://en.wikipedia.org/wiki/Neptunium',
    category: 'Actinide',
    electronConfiguration: [2, 8, 18, 32, 22, 9, 2],
    xpos: 7,
    ypos: 10,
  },
  {
    atomicNumber: 94,
    symbol: 'Pu',
    name: 'Plutonium',
    atomicMass: 244,
    density: 19.816,
    phase: 'Solid',
    meltingPoint: 912.5,
    boilingPoint: 3505,
    discoveryYear: 1940,
    discoverer: 'Glenn T. Seaborg, Edwin McMillan, Joseph W. Kennedy, Arthur C. Wahl',
    summary: 'Plutonium is a chemical element with the symbol Pu and atomic number 94. It is a radioactive actinide metal. It is the most important transuranic isotope for nuclear weapons and nuclear power.',
    externalLink: 'https://en.wikipedia.org/wiki/Plutonium',
    category: 'Actinide',
    electronConfiguration: [2, 8, 18, 32, 24, 8, 2],
    xpos: 8,
    ypos: 10,
  },
  {
    atomicNumber: 95,
    symbol: 'Am',
    name: 'Americium',
    atomicMass: 243,
    density: 12,
    phase: 'Solid',
    meltingPoint: 1449,
    boilingPoint: 2880,
    discoveryYear: 1944,
    discoverer: 'Glenn T. Seaborg, Ralph A. James, Leon O. Morgan, Albert Ghiorso',
    summary: 'Americium is a chemical element with the symbol Am and atomic number 95. It is a radioactive transuranic actinide metal. Americium is used in smoke detectors and as a source of alpha particles.',
    externalLink: 'https://en.wikipedia.org/wiki/Americium',
    category: 'Actinide',
    electronConfiguration: [2, 8, 18, 32, 25, 8, 2],
    xpos: 9,
    ypos: 10,
  },
  {
    atomicNumber: 96,
    symbol: 'Cm',
    name: 'Curium',
    atomicMass: 247,
    density: 13.5,
    phase: 'Solid',
    meltingPoint: 1613,
    boilingPoint: 3383,
    discoveryYear: 1944,
    discoverer: 'Glenn T. Seaborg, Ralph A. James, Albert Ghiorso',
    summary: 'Curium is a chemical element with the symbol Cm and atomic number 96. It is a radioactive transuranic actinide metal. Curium is used in radioisotope thermoelectric generators.',
    externalLink: 'https://en.wikipedia.org/wiki/Curium',
    category: 'Actinide',
    electronConfiguration: [2, 8, 18, 32, 25, 9, 2],
    xpos: 10,
    ypos: 10,
  },
  {
    atomicNumber: 97,
    symbol: 'Bk',
    name: 'Berkelium',
    atomicMass: 247,
    density: 14.78,
    phase: 'Solid',
    meltingPoint: 1259,
    boilingPoint: 2900,
    discoveryYear: 1949,
    discoverer: 'Glenn T. Seaborg, Albert Ghiorso, Stanley G. Thompson',
    summary: 'Berkelium is a chemical element with the symbol Bk and atomic number 97. It is a radioactive transuranic actinide metal. Berkelium is used in research and in the production of other transuranic elements.',
    externalLink: 'https://en.wikipedia.org/wiki/Berkelium',
    category: 'Actinide',
    electronConfiguration: [2, 8, 18, 32, 27, 8, 2],
    xpos: 11,
    ypos: 10,
  },
  {
    atomicNumber: 98,
    symbol: 'Cf',
    name: 'Californium',
    atomicMass: 251,
    density: 15.1,
    phase: 'Solid',
    meltingPoint: 1173,
    boilingPoint: 1743,
    discoveryYear: 1950,
    discoverer: 'Glenn T. Seaborg, Stanley G. Thompson, Kenneth Street Jr., Albert Ghiorso',
    summary: 'Californium is a chemical element with the symbol Cf and atomic number 98. It is a radioactive transuranic actinide metal. Californium is used in neutron sources and in the production of other transuranic elements.',
    externalLink: 'https://en.wikipedia.org/wiki/Californium',
    category: 'Actinide',
    electronConfiguration: [2, 8, 18, 32, 28, 8, 2],
    xpos: 12,
    ypos: 10,
  },
  {
    atomicNumber: 99,
    symbol: 'Es',
    name: 'Einsteinium',
    atomicMass: 252,
    density: 8.84,
    phase: 'Solid',
    meltingPoint: 1133,
    boilingPoint: 1269,
    discoveryYear: 1952,
    discoverer: 'Albert Ghiorso et al.',
    summary: 'Einsteinium is a chemical element with the symbol Es and atomic number 99. It is a synthetic element and is highly radioactive. Einsteinium is used in research and in the production of other transuranic elements.',
    externalLink: 'https://en.wikipedia.org/wiki/Einsteinium',
    category: 'Actinide',
    electronConfiguration: [2, 8, 18, 32, 29, 8, 2],
    xpos: 13,
    ypos: 10,
  },
  {
    atomicNumber: 100,
    symbol: 'Fm',
    name: 'Fermium',
    atomicMass: 257,
    density: 9.7,
    phase: 'Solid',
    meltingPoint: 1800,
    boilingPoint: 1800,
    discoveryYear: 1952,
    discoverer: 'Albert Ghiorso et al.',
    summary: 'Fermium is a chemical element with the symbol Fm and atomic number 100. It is a synthetic element and is highly radioactive. Fermium is used in research and in the production of other transuranic elements.',
    externalLink: 'https://en.wikipedia.org/wiki/Fermium',
    category: 'Actinide',
    electronConfiguration: [2, 8, 18, 32, 30, 8, 2],
    xpos: 14,
    ypos: 10,
  },
  {
    atomicNumber: 101,
    symbol: 'Md',
    name: 'Mendelevium',
    atomicMass: 258,
    density: 10.3,
    phase: 'Solid',
    meltingPoint: 1100,
    boilingPoint: 1100,
    discoveryYear: 1955,
    discoverer: 'Albert Ghiorso, Glenn T. Seaborg, Bernard Harvey, Gregory R. Choppin, Stanley G. Thompson',
    summary: 'Mendelevium is a chemical element with the symbol Md and atomic number 101. It is a synthetic element and is highly radioactive. Mendelevium is used in research and in the production of other transuranic elements.',
    externalLink: 'https://en.wikipedia.org/wiki/Mendelevium',
    category: 'Actinide',
    electronConfiguration: [2, 8, 18, 32, 31, 8, 2],
    xpos: 15,
    ypos: 10,
  },
  {
    atomicNumber: 102,
    symbol: 'No',
    name: 'Nobelium',
    atomicMass: 259,
    density: 9.9,
    phase: 'Solid',
    meltingPoint: 1100,
    boilingPoint: 1100,
    discoveryYear: 1966,
    discoverer: 'Joint Institute for Nuclear Research',
    summary: 'Nobelium is a chemical element with the symbol No and atomic number 102. It is a synthetic element and is highly radioactive. Nobelium is used in research and in the production of other transuranic elements.',
    externalLink: 'https://en.wikipedia.org/wiki/Nobelium',
    category: 'Actinide',
    electronConfiguration: [2, 8, 18, 32, 32, 8, 2],
    xpos: 16,
    ypos: 10,
  },
  {
    atomicNumber: 103,
    symbol: 'Lr',
    name: 'Lawrencium',
    atomicMass: 262,
    density: 15.6,
    phase: 'Solid',
    meltingPoint: 1900,
    boilingPoint: 1900,
    discoveryYear: 1961,
    discoverer: 'Albert Ghiorso et al.',
    summary: 'Lawrencium is a chemical element with the symbol Lr and atomic number 103. It is a synthetic element and is highly radioactive. Lawrencium is used in research and in the production of other transuranic elements.',
    externalLink: 'https://en.wikipedia.org/wiki/Lawrencium',
    category: 'Actinide',
    electronConfiguration: [2, 8, 18, 32, 32, 8, 3],
    xpos: 17,
    ypos: 10,
  },
  {
    atomicNumber: 104,
    symbol: 'Rf',
    name: 'Rutherfordium',
    atomicMass: 267,
    density: 23.2,
    phase: 'Synthetic',
    meltingPoint: 2400,
    boilingPoint: 5500,
    discoveryYear: 1964,
    discoverer: 'Joint Institute for Nuclear Research',
    summary: 'Rutherfordium is a chemical element with the symbol Rf and atomic number 104. It is a synthetic element and is highly radioactive. Rutherfordium is used in research and in the production of other transuranic elements.',
    externalLink: 'https://en.wikipedia.org/wiki/Rutherfordium',
    category: 'Transition Metal',
    electronConfiguration: [2, 8, 18, 32, 32, 10, 2],
    xpos: 4,
    ypos: 7,
  },
  {
    atomicNumber: 105,
    symbol: 'Db',
    name: 'Dubnium',
    atomicMass: 268,
    density: 29.3,
    phase: 'Synthetic',
    meltingPoint: 2500,
    boilingPoint: 5000,
    discoveryYear: 1968,
    discoverer: 'Joint Institute for Nuclear Research',
    summary: 'Dubnium is a chemical element with the symbol Db and atomic number 105. It is a synthetic element and is highly radioactive. Dubnium is used in research and in the production of other transuranic elements.',
    externalLink: 'https://en.wikipedia.org/wiki/Dubnium',
    category: 'Transition Metal',
    electronConfiguration: [2, 8, 18, 32, 32, 11, 2],
    xpos: 5,
    ypos: 7,
  },
  {
    atomicNumber: 106,
    symbol: 'Sg',
    name: 'Seaborgium',
    atomicMass: 271,
    density: 35,
    phase: 'Synthetic',
    meltingPoint: 2500,
    boilingPoint: 5000,
    discoveryYear: 1974,
    discoverer: 'Lawrence Berkeley Laboratory',
    summary: 'Seaborgium is a chemical element with the symbol Sg and atomic number 106. It is a synthetic element and is highly radioactive. Seaborgium is used in research and in the production of other transuranic elements.',
    externalLink: 'https://en.wikipedia.org/wiki/Seaborgium',
    category: 'Transition Metal',
    electronConfiguration: [2, 8, 18, 32, 32, 12, 2],
    xpos: 6,
    ypos: 7,
  },
  {
    atomicNumber: 107,
    symbol: 'Bh',
    name: 'Bohrium',
    atomicMass: 272,
    density: 37.1,
    phase: 'Synthetic',
    meltingPoint: 2500,
    boilingPoint: 5000,
    discoveryYear: 1976,
    discoverer: 'Joint Institute for Nuclear Research',
    summary: 'Bohrium is a chemical element with the symbol Bh and atomic number 107. It is a synthetic element and is highly radioactive. Bohrium is used in research and in the production of other transuranic elements.',
    externalLink: 'https://en.wikipedia.org/wiki/Bohrium',
    category: 'Transition Metal',
    electronConfiguration: [2, 8, 18, 32, 32, 13, 2],
    xpos: 7,
    ypos: 7,
  },
  {
    atomicNumber: 108,
    symbol: 'Hs',
    name: 'Hassium',
    atomicMass: 277,
    density: 40.7,
    phase: 'Synthetic',
    meltingPoint: 2500,
    boilingPoint: 5000,
    discoveryYear: 1984,
    discoverer: 'Gesellschaft für Schwerionenforschung',
    summary: 'Hassium is a chemical element with the symbol Hs and atomic number 108. It is a synthetic element and is highly radioactive. Hassium is used in research and in the production of other transuranic elements.',
    externalLink: 'https://en.wikipedia.org/wiki/Hassium',
    category: 'Transition Metal',
    electronConfiguration: [2, 8, 18, 32, 32, 14, 2],
    xpos: 8,
    ypos: 7,
  },
  {
    atomicNumber: 109,
    symbol: 'Mt',
    name: 'Meitnerium',
    atomicMass: 276,
    density: 37.4,
    phase: 'Synthetic',
    meltingPoint: 2500,
    boilingPoint: 5000,
    discoveryYear: 1982,
    discoverer: 'Gesellschaft für Schwerionenforschung',
    summary: 'Meitnerium is a chemical element with the symbol Mt and atomic number 109. It is a synthetic element and is highly radioactive. Meitnerium is used in research and in the production of other transuranic elements.',
    externalLink: 'https://en.wikipedia.org/wiki/Meitnerium',
    category: 'Transition Metal',
    electronConfiguration: [2, 8, 18, 32, 32, 15, 2],
    xpos: 9,
    ypos: 7,
  },
  {
    atomicNumber: 110,
    symbol: 'Ds',
    name: 'Darmstadtium',
    atomicMass: 281,
    density: 34.8,
    phase: 'Synthetic',
    meltingPoint: 2500,
    boilingPoint: 5000,
    discoveryYear: 1994,
    discoverer: 'Gesellschaft für Schwerionenforschung',
    summary: 'Darmstadtium is a chemical element with the symbol Ds and atomic number 110. It is a synthetic element and is highly radioactive. Darmstadtium is used in research and in the production of other transuranic elements.',
    externalLink: 'https://en.wikipedia.org/wiki/Darmstadtium',
    category: 'Transition Metal',
    electronConfiguration: [2, 8, 18, 32, 32, 16, 2],
    xpos: 10,
    ypos: 7,
  },
  {
    atomicNumber: 111,
    symbol: 'Rg',
    name: 'Roentgenium',
    atomicMass: 282,
    density: 28.7,
    phase: 'Synthetic',
    meltingPoint: 2500,
    boilingPoint: 5000,
    discoveryYear: 1994,
    discoverer: 'Gesellschaft für Schwerionenforschung',
    summary: 'Roentgenium is a chemical element with the symbol Rg and atomic number 111. It is a synthetic element and is highly radioactive. Roentgenium is used in research and in the production of other transuranic elements.',
    externalLink: 'https://en.wikipedia.org/wiki/Roentgenium',
    category: 'Transition Metal',
    electronConfiguration: [2, 8, 18, 32, 32, 17, 2],
    xpos: 11,
    ypos: 7,
  },
  {
    atomicNumber: 112,
    symbol: 'Cn',
    name: 'Copernicium',
    atomicMass: 285,
    density: 23.7,
    phase: 'Synthetic',
    meltingPoint: 283,
    boilingPoint: 357,
    discoveryYear: 1996,
    discoverer: 'Gesellschaft für Schwerionenforschung',
    summary: 'Copernicium is a chemical element with the symbol Cn and atomic number 112. It is a synthetic element and is highly radioactive. Copernicium is used in research and in the production of other transuranic elements.',
    externalLink: 'https://en.wikipedia.org/wiki/Copernicium',
    category: 'Transition Metal',
    electronConfiguration: [2, 8, 18, 32, 32, 18, 2],
    xpos: 12,
    ypos: 7,
  },
  {
    atomicNumber: 113,
    symbol: 'Nh',
    name: 'Nihonium',
    atomicMass: 286,
    density: 16,
    phase: 'Synthetic',
    meltingPoint: 700,
    boilingPoint: 1400,
    discoveryYear: 2003,
    discoverer: 'RIKEN',
    summary: 'Nihonium is a chemical element with the symbol Nh and atomic number 113. It is a synthetic element and is highly radioactive. Nihonium is used in research and in the production of other transuranic elements.',
    externalLink: 'https://en.wikipedia.org/wiki/Nihonium',
    category: 'Post-Transition Metal',
    electronConfiguration: [2, 8, 18, 32, 32, 18, 3],
    xpos: 13,
    ypos: 7,
  },
  {
    atomicNumber: 114,
    symbol: 'Fl',
    name: 'Flerovium',
    atomicMass: 289,
    density: 14,
    phase: 'Synthetic',
    meltingPoint: 270,
    boilingPoint: 340,
    discoveryYear: 1999,
    discoverer: 'Joint Institute for Nuclear Research',
    summary: 'Flerovium is a chemical element with the symbol Fl and atomic number 114. It is a synthetic element and is highly radioactive. Flerovium is used in research and in the production of other transuranic elements.',
    externalLink: 'https://en.wikipedia.org/wiki/Flerovium',
    category: 'Post-Transition Metal',
    electronConfiguration: [2, 8, 18, 32, 32, 18, 4],
    xpos: 14,
    ypos: 7,
  },
  {
    atomicNumber: 115,
    symbol: 'Mc',
    name: 'Moscovium',
    atomicMass: 290,
    density: 13.5,
    phase: 'Synthetic',
    meltingPoint: 670,
    boilingPoint: 1400,
    discoveryYear: 2003,
    discoverer: 'Joint Institute for Nuclear Research',
    summary: 'Moscovium is a chemical element with the symbol Mc and atomic number 115. It is a synthetic element and is highly radioactive. Moscovium is used in research and in the production of other transuranic elements.',
    externalLink: 'https://en.wikipedia.org/wiki/Moscovium',
    category: 'Post-Transition Metal',
    electronConfiguration: [2, 8, 18, 32, 32, 18, 5],
    xpos: 15,
    ypos: 7,
  },
  {
    atomicNumber: 116,
    symbol: 'Lv',
    name: 'Livermorium',
    atomicMass: 293,
    density: 12.9,
    phase: 'Synthetic',
    meltingPoint: 637,
    boilingPoint: 1085,
    discoveryYear: 2000,
    discoverer: 'Joint Institute for Nuclear Research',
    summary: 'Livermorium is a chemical element with the symbol Lv and atomic number 116. It is a synthetic element and is highly radioactive. Livermorium is used in research and in the production of other transuranic elements.',
    externalLink: 'https://en.wikipedia.org/wiki/Livermorium',
    category: 'Post-Transition Metal',
    electronConfiguration: [2, 8, 18, 32, 32, 18, 6],
    xpos: 16,
    ypos: 7,
  },
  {
    atomicNumber: 117,
    symbol: 'Ts',
    name: 'Tennessine',
    atomicMass: 294,
    density: 7.1,
    phase: 'Synthetic',
    meltingPoint: 623,
    boilingPoint: 883,
    discoveryYear: 2010,
    discoverer: 'Joint Institute for Nuclear Research, Oak Ridge National Laboratory',
    summary: 'Tennessine is a chemical element with the symbol Ts and atomic number 117. It is a synthetic element and is highly radioactive. Tennessine is used in research and in the production of other transuranic elements.',
    externalLink: 'https://en.wikipedia.org/wiki/Tennessine',
    category: 'Metalloid',
    electronConfiguration: [2, 8, 18, 32, 32, 18, 7],
    xpos: 17,
    ypos: 7,
  },
  {
    atomicNumber: 118,
    symbol: 'Og',
    name: 'Oganesson',
    atomicMass: 294,
    density: 5.0,
    phase: 'Synthetic',
    meltingPoint: 258,
    boilingPoint: 263,
    discoveryYear: 2006,
    discoverer: 'Joint Institute for Nuclear Research',
    summary: 'Oganesson is a chemical element with the symbol Og and atomic number 118. It is a synthetic element and is highly radioactive. Oganesson is used in research and in the production of other transuranic elements.',
    externalLink: 'https://en.wikipedia.org/wiki/Oganesson',
    category: 'Noble Gas',
    electronConfiguration: [2, 8, 18, 32, 32, 18, 8],
    xpos: 18,
    ypos: 7,
  },
];
